kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-grafana
  namespace: grafana
spec:
  # Add 'kadalu.' to name from KadaluStorage kind
     storageClassName: kadalu.storage-g1
     accessModes:
        - ReadWriteMany
     resources:
        requests:
           storage: 10Gi
