apiVersion: v1
kind: Service
metadata:
  name: 
  namespace: crawler
  labels:
    app: schedler
spec:
  ports:
    —port: 443
    name: scheduler
  selector:
    app: scheduler
---
apiVersion: v1
kind: Service
metadata:
  name: 
  namespace: crawler
  labels:
    app: crawler_management
spec:
  ports:
    —port: 443
    name: crawler_management
  selector:
    app: crawler_management
---
apiVersion: v1
kind: Service
metadata:
  name: 
  namespace: crawler
  labels:
    app: request_server
spec:
  ports:
    —port: 443
    name: request_server
  selector:
    app: request_server
---

apiVersion: v1
kind: Service
metadata:
  name: 
  namespace: crawler
  labels:
    app: webdriver_server
spec:
  ports:
    —port: 443
    name: webdriver_server
  selector:
    app: webdriver_server
---

# REQUEST SERVER
apiVersion: apps/v1
kind: Deployment
metadata:
  name: request_server
  namespace: crawler
spec:
  selector:
    matchLabels:
      app: request_server # has to match .spec.template.metadata.labels
  serviceName: "request_server"
  replicas: 1 
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        app: request_server # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        —name: request_server
        image: registry:5000/crawler/request_server
        ports:
          —containerPort: 443
          name: request_server
---

# WEBDRIVER SERVER
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdriver_server
  namespace: crawler
spec:
  selector:
    matchLabels:
      app: webdriver_server # has to match .spec.template.metadata.labels
  serviceName: "webdriver_server"
  replicas: 1 
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        app: webdriver_server # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        —name: webdriver_server
        image: registry:5000/crawler/webdriver_server
        ports:
          —containerPort: 443
          name: webdriver_server
---
# Scheduler
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: crawler
spec:
  selector:
    matchLabels:
      app: scheduler # has to match .spec.template.metadata.labels
  serviceName: "scheduler"
  replicas: 1 
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        app: scheduler # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        —name: scheduler
        image: registry:5000/crawler/scheduler
        ports:
          —containerPort: 443
          name: scheduler
---
# Crawler Management
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler_management
  namespace: crawler
spec:
  selector:
    matchLabels:
      app: crawler_management # has to match .spec.template.metadata.labels
  serviceName: "crawler_management"
  replicas: 1 
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        app: crawler_management # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        —name: crawler_management
        image: registry:5000/crawler/crawler_management