sudo docker stop  nuget-server
sudo docker stop  registry
sudo docker stop  gitea
sudo docker stop  jenkins
sudo docker stop  nginx
sudo docker stop  redis
sudo docker stop  mongodb
sudo docker stop  prom
sudo docker stop  es
sudo docker stop  kibana
sudo docker stop  grafana
sudo docker stop  rabbitmq
