// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/rpc.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Microservice.Grpc.Core {

  /// <summary>Holder for reflection information generated from Protos/rpc.proto</summary>
  public static partial class RpcReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/rpc.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RpcReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBQcm90b3MvcnBjLnByb3RvEgNycGMiNAoKUnBjUmVxdWVzdBIPCgdyZXF1",
            "ZXN0GAEgASgJEhUKDWNvcnJlbGF0aW9uaWQYAiABKAkiQgoIUnBjUmVwbHkS",
            "DwoHcmVwb25zZRgBIAEoCRIVCg1jb3JyZWxhdGlvbmlkGAIgASgJEg4KBmVy",
            "cm9ycxgDIAEoCTIwCgNScGMSKQoHRXhlY3V0ZRIPLnJwYy5ScGNSZXF1ZXN0",
            "Gg0ucnBjLlJwY1JlcGx5QhuqAhhNaWNyb3NlcnZpY2UuR3JwYy5TZXJ2ZXJi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Microservice.Grpc.Core.RpcRequest), global::Microservice.Grpc.Core.RpcRequest.Parser, new[]{ "Request", "Correlationid" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Microservice.Grpc.Core.RpcReply), global::Microservice.Grpc.Core.RpcReply.Parser, new[]{ "Reponse", "Correlationid", "Errors" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RpcRequest : pb::IMessage<RpcRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RpcRequest> _parser = new pb::MessageParser<RpcRequest>(() => new RpcRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RpcRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Microservice.Grpc.Core.RpcReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcRequest(RpcRequest other) : this() {
      request_ = other.request_;
      correlationid_ = other.correlationid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcRequest Clone() {
      return new RpcRequest(this);
    }

    /// <summary>Field number for the "request" field.</summary>
    public const int RequestFieldNumber = 1;
    private string request_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Request {
      get { return request_; }
      set {
        request_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "correlationid" field.</summary>
    public const int CorrelationidFieldNumber = 2;
    private string correlationid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Correlationid {
      get { return correlationid_; }
      set {
        correlationid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RpcRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RpcRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Request != other.Request) return false;
      if (Correlationid != other.Correlationid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Request.Length != 0) hash ^= Request.GetHashCode();
      if (Correlationid.Length != 0) hash ^= Correlationid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Request.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Request);
      }
      if (Correlationid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Correlationid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Request.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Request);
      }
      if (Correlationid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Correlationid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Request.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Request);
      }
      if (Correlationid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Correlationid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RpcRequest other) {
      if (other == null) {
        return;
      }
      if (other.Request.Length != 0) {
        Request = other.Request;
      }
      if (other.Correlationid.Length != 0) {
        Correlationid = other.Correlationid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Request = input.ReadString();
            break;
          }
          case 18: {
            Correlationid = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Request = input.ReadString();
            break;
          }
          case 18: {
            Correlationid = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RpcReply : pb::IMessage<RpcReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RpcReply> _parser = new pb::MessageParser<RpcReply>(() => new RpcReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RpcReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Microservice.Grpc.Core.RpcReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcReply(RpcReply other) : this() {
      reponse_ = other.reponse_;
      correlationid_ = other.correlationid_;
      errors_ = other.errors_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcReply Clone() {
      return new RpcReply(this);
    }

    /// <summary>Field number for the "reponse" field.</summary>
    public const int ReponseFieldNumber = 1;
    private string reponse_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Reponse {
      get { return reponse_; }
      set {
        reponse_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "correlationid" field.</summary>
    public const int CorrelationidFieldNumber = 2;
    private string correlationid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Correlationid {
      get { return correlationid_; }
      set {
        correlationid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "errors" field.</summary>
    public const int ErrorsFieldNumber = 3;
    private string errors_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Errors {
      get { return errors_; }
      set {
        errors_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RpcReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RpcReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Reponse != other.Reponse) return false;
      if (Correlationid != other.Correlationid) return false;
      if (Errors != other.Errors) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Reponse.Length != 0) hash ^= Reponse.GetHashCode();
      if (Correlationid.Length != 0) hash ^= Correlationid.GetHashCode();
      if (Errors.Length != 0) hash ^= Errors.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Reponse.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Reponse);
      }
      if (Correlationid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Correlationid);
      }
      if (Errors.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Errors);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Reponse.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Reponse);
      }
      if (Correlationid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Correlationid);
      }
      if (Errors.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Errors);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Reponse.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Reponse);
      }
      if (Correlationid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Correlationid);
      }
      if (Errors.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Errors);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RpcReply other) {
      if (other == null) {
        return;
      }
      if (other.Reponse.Length != 0) {
        Reponse = other.Reponse;
      }
      if (other.Correlationid.Length != 0) {
        Correlationid = other.Correlationid;
      }
      if (other.Errors.Length != 0) {
        Errors = other.Errors;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Reponse = input.ReadString();
            break;
          }
          case 18: {
            Correlationid = input.ReadString();
            break;
          }
          case 26: {
            Errors = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Reponse = input.ReadString();
            break;
          }
          case 18: {
            Correlationid = input.ReadString();
            break;
          }
          case 26: {
            Errors = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
