kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-git
  namespace: git
spec:
     claimRef: null
  # Add 'kadalu.' to name from KadaluStorage kind
     storageClassName: kadalu.storage-g1
     accessModes:
        - ReadWriteMany
     resources:
        requests:
           storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-git-postgres
  namespace: git
spec:
     claimRef: null
  # Add 'kadalu.' to name from KadaluStorage kind
     storageClassName: kadalu.storage-g1
     accessModes:
        - ReadWriteMany
     resources:
        requests:
           storage: 10Gi
