{
 "title": "Crawler Lite",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Exchange - Crawl",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "data_incoming{context=\"CrawlRequest\"}",
     "legendFormat": "Incoming-{{context}}"
    },
    {
     "expr": "data_transformed{context=\"CrawlRequest\"}",
     "legendFormat": "Transformed-{{context }}"
    },
    {
     "expr": "data_published{context=\"CrawlResponseModel\"} or data_published{context=\"CrawlEsResponseModel\"} ",
     "legendFormat": "published-{{context }}"
    },
    {
     "expr": "errors{context != \"UriDataModel\"}",
     "legendFormat": "errors-{{context}}"
    }
   ]
  },
  {
   "title": "Exchange - Uri",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "data_incoming{context=\"CrawlUri\"}",
     "legendFormat": "Incoming-{{context}}"
    },
    {
     "expr": "data_transformed{context=\"CrawlUri\"}",
     "legendFormat": "Transformed-{{context }}"
    },
    {
     "expr": "data_published{context=\"UriDataModel\"}",
     "legendFormat": "published-{{context }}"
    },
    {
     "expr": "errors{context=\"UriDataModel\"}",
     "legendFormat": "errors-{{context}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Scheduler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "job_uri_collection", "legendFormat": "collector: {{context}}" },
    { "expr": "job_uri_found", "legendFormat": "uri_found: {{context}}" },
    { "expr": "job_uri_onetime", "legendFormat": "schedule-once" },
    {
     "expr": "job_unscheduled",
     "legendFormat": "Unscheduled-publish: {{context}}"
    }
   ]
  },
  {
   "title": "Grpc",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_counters{context=\"request_server_success\"}",
     "legendFormat": "success-{{job}}"
    },
    {
     "expr": "grpc_counters{context=\"request_sent\"}",
     "legendFormat": "sent-{{job}}"
    },
    {
     "expr": "grpc_counters{context=\"error\"}",
     "legendFormat": "error-{{job}}"
    }
   ]
  },
  {
   "title": "Crawls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "crawls{context=\"started\"}",
     "legendFormat": "started"
    },
    {
     "expr": "crawls{context=\"completed\"}",
     "legendFormat": "completed"
    },
    {
     "expr": "crawls{context=\"failed\"}",
     "legendFormat": "error"
    },
    { "expr": "crawl_uri_found", "legendFormat": "new_uri: {{context}}" }
   ]
  },
  {
   "title": "Web Driver",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "crawler_web_driver", "legendFormat": "success" },
    { "expr": "crawler_web_driver_fail", "legendFormat": "failed" }
   ]
  },
  {
   "title": "Memory MBs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dotnet_total_memory_bytes[30s])/(1000*1000)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Request Duration Mean in ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "request_duration_in_ms_sum{job=\"configurationServer\"}/request_duration_in_ms_count{job=\"configurationServer\"}",
     "legendFormat": "Configuration Server"
    },
    {
     "expr": "request_duration_in_ms_sum{job=\"requestManagerServer\"}/request_duration_in_ms_count{job=\"requestManagerServer\"}",
     "legendFormat": "Request Manager"
    },
    {
     "expr": "request_duration_in_ms_sum{job=\"webDriverServer\"}/request_duration_in_ms_count{job=\"webDriverServer\"}",
     "legendFormat": "Web Driver"
    }
   ]
  },
  {
   "title": "Cpu Percentage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[30s]) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Services",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  }
 ]
}