{
 "title": "Crawler",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Crawls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "crawler{context=\"request\"}",
     "legendFormat": "Requests"
    },
    {
     "expr": "crawler{context=\"completed\"}",
     "legendFormat": "Completed"
    },
    {
     "expr": "crawler{context=\"failed\"}"
    }
   ]
  },
  {
   "title": "Grpc",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_counters{context=\"request_server_success\"}",
     "legendFormat": "success-{{job}}"
    },
    {
     "expr": "grpc_counters{context=\"request_sent\"}",
     "legendFormat": "sent-{{job}}"
    },
    {
     "expr": "grpc_counters{context=\"error\"}",
     "legendFormat": "error-{{job}}"
    }
   ]
  },
  {
   "title": "Memory MBs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dotnet_total_memory_bytes[30s])/(1000*1000)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Web Driver",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "crawler_web_driver", "legendFormat": "{{Context}}" }
   ]
  },
  {
   "title": "Cpu Percentage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[30s]) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Request Duration Mean in ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "request_duration_in_ms_sum{job=\"configurationServer\"}/request_duration_in_ms_count{job=\"configurationServer\"}",
     "legendFormat": "Configuration Server"
    },
    {
     "expr": "request_duration_in_ms_sum{job=\"requestManagerServer\"}/request_duration_in_ms_count{job=\"requestManagerServer\"}",
     "legendFormat": "Request Manager"
    },
    {
     "expr": "request_duration_in_ms_sum{job=\"webDriverServer\"}/request_duration_in_ms_count{job=\"webDriverServer\"}",
     "legendFormat": "Web Driver"
    }
   ]
  },
  {
   "title": "Success",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "fields.Application",
       "id": "1",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "message:\"Successfully processed\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Activity",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "fields.Application",
       "id": "1",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "-message:\"/metrics\" AND -message:\"Web Driver Cleanup\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Crawl Exceptions",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "fields.Application",
       "id": "1",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "message:\"Failed to Read/Process Crawl Request\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Error",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "fields.Application",
       "id": "1",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "message:\"Error\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}