kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-jupyter
  namespace: jupyter
spec:
     claimRef: null
  # Add 'kadalu.' to name from KadaluStorage kind
     storageClassName: kadalu.storage-g1
     accessModes:
        - ReadWriteMany
     resources:
        requests:
           storage: 10Gi
